### ISSUE TITLE
Role and Able Use

### ISSUE THREAD

**Issue by jim-rosales** [Ctucker9233/CodecademyProIntensive#1]
Excellent job adding the role and aria-label to increase the backward compatibility for older browsers!

https://github.com/Ctucker9233/CodecademyProIntensive/blob/2ac32a57d3da13f0e4f41defb22d98ea3d22da80/ware-house-starting-code/index.html#L16

**Comment by Ctucker9233** [comment]
@jim-rosales Thank you.
